# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(default='Maintain', max_length=255),
        ),
    ]
