# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0003_auto_20160929_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.IntegerField(),
        ),
    ]
