# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg_app', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('height', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
