# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 18:46
from __future__ import unicode_literals

import apps.login_reg_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, validators=[apps.login_reg_app.models.validateName]),
        ),
    ]
