# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0005_auto_20160929_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
