# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blueSquirrelsFitnessApp', '0003_auto_20160927_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
