# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueSquirrelsFitnessApp', '0006_auto_20160930_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
